version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=model-eval
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: server
    command: pnpm --filter @model-eval/server dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=8000
      - MONGODB_URI=mongodb://mongodb:27017/model-eval
      - CORS_ORIGINS=http://localhost:3000
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: client
    command: pnpm --filter @model-eval/client dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - server
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000/api
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge